### ISSUE TITLE
add option to configure destination folder

### ISSUE THREAD

**Issue by arve0** [arve0/metalsmith-changed#1]
> For some reason metalsmith-changed wasn't ignoring all of the files I expected it to, so I created this for myself.

I would love to fix that. Can you elaborate, @mrajo?

**Comment by mrajo** [comment]
Hey @arve0,

You probably don't have to worry about it. I'll try to explain really quick what I was doing.

At first, I was filtering out the unchanged source files with a quick and dirty ad hoc plugin before I realized metalsmith-changed existed. I switched to that and had a problem with it due to gulpsmith being unaware of the destination folder, so I forked metalsmith-changed to fix that. Then I had the problem where the build targets were different from my ad hoc plugin (the final files object were different). I turned the working folder of my fork into a mess trying to debug it. Our source code was similar so I couldn't figure out the difference at the time, so I moved my ad hoc plugin code to a plugin and posted it for myself. I didn't mean to suggest yours didn't work and didn't expect it to be noticed. I just couldn't figure out why it was working differently at the time and I wanted to save it for myself until I did figure it out.

I didn't think it was a problem with metalsmith-changed, honestly. I was thinking it was just something specific to my metalsmith build sequence or something else I was doing wrong (I'm kind of new to metalsmith). I'll see if I can recreate a test or fix what I was doing.

**Comment by arve0** [comment]
I guess configuration of destination folder can be useful for other too then. I'll implement it if I find some time.

**Comment by mrajo** [comment]
I tried going back to figure out exactly what problems I was experiencing before. Sure enough, it was just as I expected - it was simply a problems specific to my build working with other plugins. I tried documenting some of the problems through tests and pushed a couple changes that made it work in my build the way I expected it to work. You can see them in my forked copy: https://github.com/mrajo/metalsmith-changed/tree/mrajo.

The bulk of my problems were caused by using gulpsmith along with non-default source and destination folders (gulpsmith works fine if you are using default paths) and metalsmith-permalinks.

**Comment by jmatsushita** [comment]
I think that's a great addition and the fork works for me.

**Comment by arve0** [comment]
Fixed in #5, only input ctimes is considered if a file should build.
